-- QualityHub application audit trail (Oracle 12c+)
-- Run this only when the deployment DB user cannot execute SQLAlchemy
-- Base.metadata.create_all(). The application otherwise creates the table.

CREATE TABLE qap_audit_logs (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type VARCHAR2(40) NOT NULL,
    action VARCHAR2(80) NOT NULL,
    outcome VARCHAR2(20) NOT NULL,
    actor_id NUMBER NULL REFERENCES qap_users(id),
    actor_username VARCHAR2(150) NULL,
    actor_name VARCHAR2(150) NULL,
    actor_roles VARCHAR2(500) NULL,
    method VARCHAR2(10) NULL,
    path VARCHAR2(500) NULL,
    status_code NUMBER NULL,
    target_type VARCHAR2(64) NULL,
    target_id VARCHAR2(100) NULL,
    target_name VARCHAR2(255) NULL,
    details CLOB NULL,
    ip_address VARCHAR2(64) NULL,
    user_agent VARCHAR2(500) NULL,
    request_id VARCHAR2(64) NULL,
    created_at DATE DEFAULT SYSDATE NOT NULL
);

CREATE INDEX ix_qap_audit_event ON qap_audit_logs(event_type);
CREATE INDEX ix_qap_audit_action ON qap_audit_logs(action);
CREATE INDEX ix_qap_audit_outcome ON qap_audit_logs(outcome);
CREATE INDEX ix_qap_audit_actor ON qap_audit_logs(actor_id);
CREATE INDEX ix_qap_audit_created ON qap_audit_logs(created_at);
CREATE INDEX ix_qap_audit_request ON qap_audit_logs(request_id);

-- Defense in depth: application audit rows are append-only even for a DB
-- account that has broad table DML privileges. Retention/purge must use a
-- separately controlled DBA process that temporarily disables this trigger.
CREATE OR REPLACE TRIGGER trg_qap_audit_immutable
BEFORE UPDATE OR DELETE ON qap_audit_logs
BEGIN
    RAISE_APPLICATION_ERROR(-20001, 'Audit log rows are immutable');
END;
/
