-- QA Workspaces: removes the one-QA-department ceiling while preserving the
-- existing COE - Quality Assurance team as the initial default workspace.
-- Safe to re-run. Apply before deploying code that references these columns.

BEGIN
  EXECUTE IMMEDIATE 'CREATE TABLE qap_qa_workspaces (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_key VARCHAR2(40) NOT NULL UNIQUE,
    name VARCHAR2(150) NOT NULL UNIQUE,
    description CLOB,
    is_active NUMBER(1) DEFAULT 1 NOT NULL,
    is_default NUMBER(1) DEFAULT 0 NOT NULL,
    created_by_id NUMBER REFERENCES qap_users(id),
    created_at TIMESTAMP,
    updated_at TIMESTAMP
  )';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE TABLE qap_qa_workspace_members (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id NUMBER NOT NULL REFERENCES qap_qa_workspaces(id),
    user_id NUMBER NOT NULL REFERENCES qap_users(id),
    role VARCHAR2(40) NOT NULL,
    is_active NUMBER(1) DEFAULT 1 NOT NULL,
    created_at TIMESTAMP,
    CONSTRAINT uq_qap_qawm_ws_user_role UNIQUE (workspace_id,user_id,role)
  )';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE TABLE qap_qa_workspace_coverage (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id NUMBER NOT NULL REFERENCES qap_qa_workspaces(id),
    department_id NUMBER REFERENCES qap_departments(id),
    application_master_id NUMBER REFERENCES qap_application_master(id),
    request_type VARCHAR2(80),
    priority NUMBER DEFAULT 100 NOT NULL,
    is_active NUMBER(1) DEFAULT 1 NOT NULL,
    created_at TIMESTAMP
  )';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE qap_users ADD (preferred_qa_workspace_id NUMBER REFERENCES qap_qa_workspaces(id))';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1430 THEN RAISE; END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE qap_requests ADD (qa_workspace_id NUMBER REFERENCES qap_qa_workspaces(id))';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1430 THEN RAISE; END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE qap_requests ADD (workspace_routing_status VARCHAR2(24) DEFAULT ''PENDING'' NOT NULL)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1430 THEN RAISE; END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE qap_test_projects ADD (qa_workspace_id NUMBER REFERENCES qap_qa_workspaces(id))';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1430 THEN RAISE; END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE qap_suppression_requests ADD (qa_workspace_id NUMBER REFERENCES qap_qa_workspaces(id))';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1430 THEN RAISE; END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE qap_signoffs ADD (qa_workspace_id NUMBER REFERENCES qap_qa_workspaces(id))';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1430 THEN RAISE; END IF;
END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE INDEX ix_qap_req_qaws ON qap_requests(qa_workspace_id)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE INDEX ix_qap_proj_qaws ON qap_test_projects(qa_workspace_id)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE INDEX ix_qap_sup_qaws ON qap_suppression_requests(qa_workspace_id)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE INDEX ix_qap_sign_qaws ON qap_signoffs(qa_workspace_id)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
/

MERGE INTO qap_qa_workspaces target
USING (SELECT 'COE-QA' workspace_key, 'COE Quality Assurance' name FROM dual) source
ON (target.workspace_key = source.workspace_key)
WHEN NOT MATCHED THEN INSERT
  (workspace_key,name,description,is_active,is_default,created_at,updated_at)
  VALUES (source.workspace_key,source.name,'Migrated default QA workspace',1,1,SYSTIMESTAMP,SYSTIMESTAMP);

INSERT INTO qap_qa_workspace_members (workspace_id,user_id,role,is_active,created_at)
SELECT workspace.id, user_role.user_id, user_role.role, 1, SYSTIMESTAMP
FROM qap_qa_workspaces workspace
JOIN qap_user_roles user_role ON user_role.role IN ('QA_ENGINEER','QA_LEAD','SECURITY_ANALYST','CHIEF_MANAGER_QA','AGM_QA')
JOIN qap_users app_user ON app_user.id = user_role.user_id AND app_user.is_active = 1
WHERE workspace.workspace_key = 'COE-QA'
  AND (app_user.department = 'COE - Quality Assurance' OR EXISTS (
    SELECT 1 FROM qap_user_departments user_dept
    WHERE user_dept.user_id = app_user.id AND user_dept.department = 'COE - Quality Assurance'
  ))
  AND NOT EXISTS (
    SELECT 1 FROM qap_qa_workspace_members member
    WHERE member.workspace_id = workspace.id AND member.user_id = user_role.user_id AND member.role = user_role.role
  );

INSERT INTO qap_qa_workspace_coverage (workspace_id,department_id,priority,is_active,created_at)
SELECT workspace.id, department.id, 100, 1, SYSTIMESTAMP
FROM qap_qa_workspaces workspace JOIN qap_departments department ON department.name = 'COE - Quality Assurance'
WHERE workspace.workspace_key = 'COE-QA'
  AND NOT EXISTS (SELECT 1 FROM qap_qa_workspace_coverage coverage
                  WHERE coverage.workspace_id = workspace.id AND coverage.department_id = department.id
                    AND coverage.application_master_id IS NULL AND coverage.request_type IS NULL);

UPDATE qap_requests SET qa_workspace_id = (SELECT id FROM qap_qa_workspaces WHERE workspace_key = 'COE-QA'),
  workspace_routing_status = 'MIGRATED' WHERE qa_workspace_id IS NULL;
UPDATE qap_test_projects SET qa_workspace_id = (SELECT id FROM qap_qa_workspaces WHERE workspace_key = 'COE-QA')
  WHERE qa_workspace_id IS NULL;
UPDATE qap_suppression_requests SET qa_workspace_id = (SELECT id FROM qap_qa_workspaces WHERE workspace_key = 'COE-QA')
  WHERE qa_workspace_id IS NULL;
UPDATE qap_signoffs SET qa_workspace_id = (SELECT id FROM qap_qa_workspaces WHERE workspace_key = 'COE-QA')
  WHERE qa_workspace_id IS NULL;
COMMIT;

-- Global Workspace rollout. The physical QA-prefixed object names above are
-- retained for compatibility, but membership now applies to every user.
INSERT INTO qap_qa_workspace_members (workspace_id,user_id,role,is_active,created_at)
SELECT DISTINCT m.workspace_id,m.user_id,'WORKSPACE_MEMBER',1,SYSTIMESTAMP
FROM qap_qa_workspace_members m
WHERE m.is_active=1 AND NOT EXISTS (
  SELECT 1 FROM qap_qa_workspace_members x
  WHERE x.workspace_id=m.workspace_id AND x.user_id=m.user_id
    AND x.role='WORKSPACE_MEMBER'
);

INSERT INTO qap_qa_workspace_members (workspace_id,user_id,role,is_active,created_at)
SELECT COALESCE(
         (SELECT MIN(id) FROM qap_qa_workspaces WHERE is_active=1 AND is_default=1),
         (SELECT MIN(id) FROM qap_qa_workspaces WHERE is_active=1)
       ),u.id,'WORKSPACE_MEMBER',1,SYSTIMESTAMP
FROM qap_users u
WHERE u.is_active=1
  AND EXISTS (SELECT 1 FROM qap_qa_workspaces WHERE is_active=1)
  AND NOT EXISTS (
    SELECT 1 FROM qap_qa_workspace_members m
    WHERE m.user_id=u.id AND m.is_active=1
  );

UPDATE qap_users u SET preferred_qa_workspace_id=(
  SELECT MIN(m.workspace_id) FROM qap_qa_workspace_members m
  WHERE m.user_id=u.id AND m.is_active=1
)
WHERE u.is_active=1 AND u.preferred_qa_workspace_id IS NULL;

DELETE FROM qap_qa_workspace_members WHERE role='WORKSPACE_VIEWER';

-- Normalize the earlier role-per-workspace model. Capabilities already live
-- in qap_user_roles; the workspace link now records only where a user works.
MERGE INTO qap_user_roles target
USING (
  SELECT DISTINCT user_id,role FROM qap_qa_workspace_members
  WHERE role IN ('QA_ENGINEER','QA_LEAD','SECURITY_ANALYST','CHIEF_MANAGER_QA','AGM_QA')
) source
ON (target.user_id=source.user_id AND target.role=source.role)
WHEN NOT MATCHED THEN INSERT (user_id,role) VALUES (source.user_id,source.role);

DELETE FROM qap_qa_workspace_members WHERE role <> 'WORKSPACE_MEMBER';
COMMIT;
