import csv
import datetime
import io
from fastapi import APIRouter, Depends, HTTPException, Query
from fastapi.responses import StreamingResponse
from sqlalchemy.orm import Session

from .. import models
from ..database import get_db
from ..deps import get_current_user
from .reports import REPORT_REGISTRY

router = APIRouter(prefix="/api/export", tags=["download-export-centre"])


@router.get("/reports")
def available_reports(current_user: models.User = Depends(get_current_user)):
    return sorted(REPORT_REGISTRY.keys())


def _rows_to_xlsx(rows, meta: dict) -> io.BytesIO:
    from openpyxl import Workbook
    wb = Workbook()
    ws = wb.active
    ws.title = "Report"

    ws.append(["Report Name", meta["report_name"]])
    ws.append(["Module / Screen", meta["module"]])
    ws.append(["Generated At", meta["generated_at"]])
    ws.append(["Generated By", meta["generated_by"]])
    ws.append(["Applied Filters", meta["filters"] or "None"])
    ws.append(["Total Record Count", meta["total_records"]])
    ws.append([])

    if rows:
        headers = list(rows[0].keys())
        ws.append(headers)
        for row in rows:
            ws.append([str(row.get(h, "")) if row.get(h) is not None else "" for h in headers])
    else:
        ws.append(["No records found"])

    buf = io.BytesIO()
    wb.save(buf)
    buf.seek(0)
    return buf


def _rows_to_csv(rows, meta: dict) -> io.StringIO:
    buf = io.StringIO()
    writer = csv.writer(buf)
    writer.writerow(["Report Name", meta["report_name"]])
    writer.writerow(["Module / Screen", meta["module"]])
    writer.writerow(["Generated At", meta["generated_at"]])
    writer.writerow(["Generated By", meta["generated_by"]])
    writer.writerow(["Applied Filters", meta["filters"] or "None"])
    writer.writerow(["Total Record Count", meta["total_records"]])
    writer.writerow([])
    if rows:
        headers = list(rows[0].keys())
        writer.writerow(headers)
        for row in rows:
            writer.writerow([row.get(h, "") for h in headers])
    else:
        writer.writerow(["No records found"])
    buf.seek(0)
    return buf


def _fit_col_widths(headers, rows, available_width, min_w=42, max_w=190):
    """Reported bug: the Download & Export Centre's PDF export rendered every
    report (qa-request-summary, audit-evidence, etc.) with columns "not
    aligned, not fitted properly" -- e.g. "Department" showing as "ent (DBD)"
    with its start clipped off, and "Timestamp"/other trailing columns losing
    their tail past the page's right edge. Root cause: the old `Table(data,
    repeatRows=1)` call passed no `colWidths` at all and put plain strings
    (not `Paragraph`s) in every cell, so reportlab sized each column to fit
    its *longest unwrapped line* with no page-width ceiling -- a handful of
    long "Comments"/"Priority / Risk (per type)" values could make the
    table's total natural width far exceed the actual landscape-A4 page,
    silently pushing whole columns past the printable area instead of
    wrapping or shrinking to fit.

    This computes one width per column, weighted by how much text that
    column typically holds (a rough proxy: each column's ~85th-percentile
    cell length, so a handful of outlier long values don't single-handedly
    dictate the whole column's width), then rescales the whole set so it
    always sums to exactly `available_width` -- every report, regardless of
    how many columns or how verbose its content, ends up fitting the page.
    Used together with wrapping every cell in a `Paragraph` (see
    `_rows_to_pdf` below) so any text that's still too long for its column
    wraps onto extra lines (taller rows) instead of overflowing sideways.
    """
    weights = []
    for h in headers:
        lengths = sorted([len(str(h))] + [len(str(r.get(h, "") or "")) for r in rows])
        idx = min(int(len(lengths) * 0.85), len(lengths) - 1)
        weights.append(max(lengths[idx], 6))
    total_weight = sum(weights) or 1
    widths = [max(min_w, min(max_w, available_width * w / total_weight)) for w in weights]
    # Clamping to [min_w, max_w] above can drift the sum away from
    # available_width -- rescale proportionally so the columns always add up
    # to exactly the page's printable width, never more (overflow) or
    # noticeably less (an oddly narrow table with dead space on the right).
    scale = available_width / sum(widths)
    return [w * scale for w in widths]


def _rows_to_pdf(rows, meta: dict) -> io.BytesIO:
    from reportlab.lib import colors
    from reportlab.lib.pagesizes import landscape, A4
    from reportlab.lib.units import mm
    from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer
    from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet

    buf = io.BytesIO()
    left_margin = right_margin = 10 * mm
    doc = SimpleDocTemplate(
        buf, pagesize=landscape(A4), leftMargin=left_margin, rightMargin=right_margin,
        topMargin=12 * mm, bottomMargin=12 * mm, title=meta["report_name"],
    )
    styles = getSampleStyleSheet()
    cell_style = ParagraphStyle("ExportCell", parent=styles["Normal"], fontSize=6.5, leading=8)
    header_style = ParagraphStyle("ExportHeader", parent=cell_style, textColor=colors.white, fontName="Helvetica-Bold")
    elements = [
        Paragraph(meta["report_name"], styles["Title"]),
        Paragraph(f"Module/Screen: {meta['module']} | Generated By: {meta['generated_by']} | "
                  f"Generated At: {meta['generated_at']} | Filters: {meta['filters'] or 'None'} | "
                  f"Total Records: {meta['total_records']}", styles["Normal"]),
        Spacer(1, 12),
    ]
    if rows:
        headers = list(rows[0].keys())
        available_width = landscape(A4)[0] - left_margin - right_margin
        col_widths = _fit_col_widths(headers, rows, available_width)
        data = [[Paragraph(str(h), header_style) for h in headers]]
        for r in rows:
            data.append([Paragraph(_fmt_cell(r.get(h)), cell_style) for h in headers])
        table = Table(data, colWidths=col_widths, repeatRows=1)
        table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1f2937")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ("LEFTPADDING", (0, 0), (-1, -1), 3), ("RIGHTPADDING", (0, 0), (-1, -1), 3),
            ("TOPPADDING", (0, 0), (-1, -1), 2), ("BOTTOMPADDING", (0, 0), (-1, -1), 2),
        ]))
        elements.append(table)
    else:
        elements.append(Paragraph("No records found", styles["Normal"]))
    doc.build(elements)
    buf.seek(0)
    return buf


def _fmt_cell(value) -> str:
    return str(value) if value is not None else ""


@router.get("/{report_key}")
def export_report(report_key: str, format: str = Query("xlsx", pattern="^(xlsx|pdf|csv)$"),
                   filters: str = "", db: Session = Depends(get_db),
                   current_user: models.User = Depends(get_current_user)):
    """
    Module 11: Download & Export Centre. Streams the requested report/screen data
    in Excel, PDF or CSV, with report metadata (name, module, generated by/at,
    filters, record count) embedded per section 4.11.4. RBAC per 4.11.5 is
    enforced by requiring an authenticated user; visibility of underlying data
    already follows each report's own query scope.
    """
    fn = REPORT_REGISTRY.get(report_key)
    if not fn:
        raise HTTPException(404, f"Unknown report '{report_key}'. See /api/export/reports for valid keys.")
    rows = fn(db=db, current_user=current_user)

    meta = {
        "report_name": report_key.replace("-", " ").title(),
        "module": report_key,
        "generated_at": models.now().strftime("%Y-%m-%d %H:%M:%S UTC"),
        "generated_by": current_user.full_name,
        "filters": filters,
        "total_records": len(rows),
    }

    filename_base = f"{report_key}_{datetime.date.today().isoformat()}"

    if format == "xlsx":
        buf = _rows_to_xlsx(rows, meta)
        return StreamingResponse(
            buf, media_type="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
            headers={"Content-Disposition": f'attachment; filename="{filename_base}.xlsx"'},
        )
    if format == "csv":
        buf = _rows_to_csv(rows, meta)
        return StreamingResponse(
            iter([buf.getvalue()]), media_type="text/csv",
            headers={"Content-Disposition": f'attachment; filename="{filename_base}.csv"'},
        )
    buf = _rows_to_pdf(rows, meta)
    return StreamingResponse(
        buf, media_type="application/pdf",
        headers={"Content-Disposition": f'attachment; filename="{filename_base}.pdf"'},
    )
