import csv
import datetime
import io
from fastapi import APIRouter, Depends, HTTPException, Query
from fastapi.responses import StreamingResponse
from sqlalchemy.orm import Session

from .. import models
from ..database import get_db
from ..deps import get_current_user
from .reports import REPORT_REGISTRY

router = APIRouter(prefix="/api/export", tags=["download-export-centre"])


@router.get("/reports")
def available_reports(current_user: models.User = Depends(get_current_user)):
    return sorted(REPORT_REGISTRY.keys())


def _rows_to_xlsx(rows, meta: dict) -> io.BytesIO:
    from openpyxl import Workbook
    wb = Workbook()
    ws = wb.active
    ws.title = "Report"

    ws.append(["Report Name", meta["report_name"]])
    ws.append(["Module / Screen", meta["module"]])
    ws.append(["Generated At", meta["generated_at"]])
    ws.append(["Generated By", meta["generated_by"]])
    ws.append(["Applied Filters", meta["filters"] or "None"])
    ws.append(["Total Record Count", meta["total_records"]])
    ws.append([])

    if rows:
        headers = list(rows[0].keys())
        ws.append(headers)
        for row in rows:
            ws.append([str(row.get(h, "")) if row.get(h) is not None else "" for h in headers])
    else:
        ws.append(["No records found"])

    buf = io.BytesIO()
    wb.save(buf)
    buf.seek(0)
    return buf


def _rows_to_csv(rows, meta: dict) -> io.StringIO:
    buf = io.StringIO()
    writer = csv.writer(buf)
    writer.writerow(["Report Name", meta["report_name"]])
    writer.writerow(["Module / Screen", meta["module"]])
    writer.writerow(["Generated At", meta["generated_at"]])
    writer.writerow(["Generated By", meta["generated_by"]])
    writer.writerow(["Applied Filters", meta["filters"] or "None"])
    writer.writerow(["Total Record Count", meta["total_records"]])
    writer.writerow([])
    if rows:
        headers = list(rows[0].keys())
        writer.writerow(headers)
        for row in rows:
            writer.writerow([row.get(h, "") for h in headers])
    else:
        writer.writerow(["No records found"])
    buf.seek(0)
    return buf


def _rows_to_pdf(rows, meta: dict) -> io.BytesIO:
    from reportlab.lib import colors
    from reportlab.lib.pagesizes import landscape, A4
    from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer
    from reportlab.lib.styles import getSampleStyleSheet

    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=landscape(A4))
    styles = getSampleStyleSheet()
    elements = [
        Paragraph(meta["report_name"], styles["Title"]),
        Paragraph(f"Module/Screen: {meta['module']} | Generated By: {meta['generated_by']} | "
                  f"Generated At: {meta['generated_at']} | Filters: {meta['filters'] or 'None'} | "
                  f"Total Records: {meta['total_records']}", styles["Normal"]),
        Spacer(1, 12),
    ]
    if rows:
        headers = list(rows[0].keys())
        data = [headers] + [[str(r.get(h, "")) if r.get(h) is not None else "" for h in headers] for r in rows]
        table = Table(data, repeatRows=1)
        table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1f2937")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTSIZE", (0, 0), (-1, -1), 7),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ]))
        elements.append(table)
    else:
        elements.append(Paragraph("No records found", styles["Normal"]))
    doc.build(elements)
    buf.seek(0)
    return buf


@router.get("/{report_key}")
def export_report(report_key: str, format: str = Query("xlsx", pattern="^(xlsx|pdf|csv)$"),
                   filters: str = "", db: Session = Depends(get_db),
                   current_user: models.User = Depends(get_current_user)):
    """
    Module 11: Download & Export Centre. Streams the requested report/screen data
    in Excel, PDF or CSV, with report metadata (name, module, generated by/at,
    filters, record count) embedded per section 4.11.4. RBAC per 4.11.5 is
    enforced by requiring an authenticated user; visibility of underlying data
    already follows each report's own query scope.
    """
    fn = REPORT_REGISTRY.get(report_key)
    if not fn:
        raise HTTPException(404, f"Unknown report '{report_key}'. See /api/export/reports for valid keys.")
    rows = fn(db=db, current_user=current_user)

    meta = {
        "report_name": report_key.replace("-", " ").title(),
        "module": report_key,
        "generated_at": datetime.datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S UTC"),
        "generated_by": current_user.full_name,
        "filters": filters,
        "total_records": len(rows),
    }

    filename_base = f"{report_key}_{datetime.date.today().isoformat()}"

    if format == "xlsx":
        buf = _rows_to_xlsx(rows, meta)
        return StreamingResponse(
            buf, media_type="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
            headers={"Content-Disposition": f'attachment; filename="{filename_base}.xlsx"'},
        )
    if format == "csv":
        buf = _rows_to_csv(rows, meta)
        return StreamingResponse(
            iter([buf.getvalue()]), media_type="text/csv",
            headers={"Content-Disposition": f'attachment; filename="{filename_base}.csv"'},
        )
    buf = _rows_to_pdf(rows, meta)
    return StreamingResponse(
        buf, media_type="application/pdf",
        headers={"Content-Disposition": f'attachment; filename="{filename_base}.pdf"'},
    )
