"""add concise change description

Revision ID: 690a9c49c4c0
Revises: 20260814_0002
Create Date: 2026-08-14 07:25:03.478468
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '690a9c49c4c0'
down_revision: Union[str, None] = '20260814_0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # The autogenerated order placed several mutually-referencing tables
    # before qap_users. Oracle validates inline foreign keys immediately, so
    # create this root table first and add the four genuinely circular
    # constraints after every participating table exists.
    op.create_table('qap_users',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('department', sa.String(length=150), nullable=True),
    sa.Column('login_type', sa.String(length=16), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('needs_role_review', sa.Boolean(), nullable=True),
    sa.Column('needs_department_selection', sa.Boolean(), nullable=True),
    sa.Column('admin_managed_only', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('qap_application_master',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('department', sa.String(length=150), nullable=True),
    sa.Column('requested_by_id', sa.Integer(), nullable=True),
    sa.Column('qa_request_id', sa.Integer(), nullable=True),
    sa.Column('app_owner_decided_by_id', sa.Integer(), nullable=True),
    sa.Column('app_owner_decided_at', sa.DateTime(), nullable=True),
    sa.Column('app_owner_comments', sa.Text(), nullable=True),
    sa.Column('decided_by_id', sa.Integer(), nullable=True),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['app_owner_decided_by_id'], ['qap_users.id'], ),
    sa.ForeignKeyConstraint(['decided_by_id'], ['qap_users.id'], ),
    sa.ForeignKeyConstraint(['requested_by_id'], ['qap_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_qap_application_master_status'), 'qap_application_master', ['status'], unique=False)
    op.create_table('qap_checklist_template_items',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.Column('module', sa.String(length=20), nullable=False),
    sa.Column('item', sa.String(length=255), nullable=False),
    sa.Column('detail', sa.String(length=255), nullable=True),
    sa.Column('is_mandatory', sa.Boolean(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('module', 'item', name='uq_qap_checklist_template_item')
    )
    op.create_table('qap_departments',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('qap_id_counters',
    sa.Column('prefix', sa.String(length=20), nullable=False),
    sa.Column('counter_date', sa.Date(), nullable=False),
    sa.Column('next_value', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('prefix', 'counter_date')
    )
    op.create_table('qap_requests',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.Column('request_id', sa.String(length=40), nullable=True),
    sa.Column('request_date', sa.Date(), nullable=True),
    sa.Column('department', sa.String(length=150), nullable=True),
    sa.Column('application_name', sa.String(length=150), nullable=False),
    sa.Column('application_owner', sa.String(length=150), nullable=True),
    sa.Column('cr_number', sa.String(length=64), nullable=True),
    sa.Column('epic_number', sa.String(length=150), nullable=True),
    sa.Column('change_type', sa.String(length=32), nullable=True),
    sa.Column('vendor_si_partner', sa.String(length=150), nullable=True),
    sa.Column('technology_stack', sa.String(length=150), nullable=True),
    sa.Column('release_version', sa.String(length=64), nullable=True),
    sa.Column('build_number', sa.String(length=64), nullable=True),
    sa.Column('environment', sa.String(length=32), nullable=True),
    sa.Column('target_promotion_environment', sa.String(length=32), nullable=True),
    sa.Column('request_types', sa.String(length=255), nullable=True),
    sa.Column('request_type_other', sa.String(length=150), nullable=True),
    sa.Column('target_release_date', sa.Date(), nullable=True),
    sa.Column('supporting_doc_path', sa.String(length=255), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('draft_child_details', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('requester_id', sa.Integer(), nullable=True),
    sa.Column('application_master_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['application_master_id'], ['qap_application_master.id'], ),
    sa.ForeignKeyConstraint(['requester_id'], ['qap_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_id')
    )
    op.create_index('ix_qap_req_dept_status_created', 'qap_requests', ['department', 'status', 'created_at'], unique=False)
    op.create_index(op.f('ix_qap_requests_status'), 'qap_requests', ['status'], unique=False)
    op.create_table('qap_system_settings',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('qap_test_case_versions',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.Column('test_case_id', sa.Integer(), nullable=False),
    sa.Column('version_major', sa.Integer(), nullable=False),
    sa.Column('version_minor', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('epic_id', sa.String(length=60), nullable=True),
    sa.Column('cr_number', sa.String(length=64), nullable=True),
    sa.Column('feature_id', sa.String(length=60), nullable=True),
    sa.Column('user_story_id', sa.String(length=60), nullable=True),
    sa.Column('test_type', sa.String(length=60), nullable=True),
    sa.Column('module_name', sa.String(length=150), nullable=True),
    sa.Column('test_scenario', sa.String(length=255), nullable=True),
    sa.Column('pre_condition', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('priority', sa.String(length=16), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('submitted_by_id', sa.Integer(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('submit_note', sa.Text(), nullable=True),
    sa.Column('reviewed_by_id', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('review_comments', sa.Text(), nullable=True),
    sa.Column('qa_lead_decided_by_id', sa.Integer(), nullable=True),
    sa.Column('qa_lead_decided_at', sa.DateTime(), nullable=True),
    sa.Column('qa_lead_decision_comments', sa.Text(), nullable=True),
    sa.Column('assigned_reviewer_id', sa.Integer(), nullable=True),
    sa.Column('assigned_qa_lead_id', sa.Integer(), nullable=True),
    sa.Column('source_version_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_qa_lead_id'], ['qap_users.id'], ),
    sa.ForeignKeyConstraint(['assigned_reviewer_id'], ['qap_users.id'], ),
    sa.ForeignKeyConstraint(['author_id'], ['qap_users.id'], ),
    sa.ForeignKeyConstraint(['qa_lead_decided_by_id'], ['qap_users.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['qap_users.id'], ),
    sa.ForeignKeyConstraint(['source_version_id'], ['qap_test_case_versions.id'], ),
    sa.ForeignKeyConstraint(['submitted_by_id'], ['qap_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('test_case_id', 'version_major', 'version_minor', name='uq_qap_tcv_case_version')
    )
    op.create_index(op.f('ix_qap_test_case_versions_test_case_id'), 'qap_test_case_versions', ['test_case_id'], unique=False)
    op.create_table('qap_test_cases',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.Column('test_case_key', sa.String(length=60), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('folder_id', sa.Integer(), nullable=True),
    sa.Column('epic_id', sa.String(length=60), nullable=True),
    sa.Column('cr_number', sa.String(length=64), nullable=True),
    sa.Column('feature_id', sa.String(length=60), nullable=True),
    sa.Column('user_story_id', sa.String(length=60), nullable=True),
    sa.Column('test_type', sa.String(length=60), nullable=True),
    sa.Column('module_name', sa.String(length=150), nullable=True),
    sa.Column('test_scenario', sa.String(length=255), nullable=True),
    sa.Column('pre_condition', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('priority', sa.String(length=16), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('version_major', sa.Integer(), nullable=False),
    sa.Column('version_minor', sa.Integer(), nullable=False),
    sa.Column('current_approved_version_id', sa.Integer(), nullable=True),
    sa.Column('current_draft_version_id', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('checked_out_by_id', sa.Integer(), nullable=True),
    sa.Column('checked_out_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_by_id', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_reason', sa.String(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['checked_out_by_id'], ['qap_users.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['qap_users.id'], ),
    sa.ForeignKeyConstraint(['current_approved_version_id'], ['qap_test_case_versions.id'], ),
    sa.ForeignKeyConstraint(['current_draft_version_id'], ['qap_test_case_versions.id'], ),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['qap_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('test_case_key')
    )
    op.create_index('ix_qap_tc_proj_deleted_created', 'qap_test_cases', ['project_id', 'is_deleted', 'created_at'], unique=False)
    op.create_index('ix_qap_tc_proj_folder_created', 'qap_test_cases', ['project_id', 'folder_id', 'created_at'], unique=False)
    op.create_table('qap_approval_actions',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('step_name', sa.String(length=64), nullable=True),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('actor_role', sa.String(length=150), nullable=True),
    sa.Column('decision', sa.String(length=64), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('previous_state', sa.String(length=30), nullable=True),
    sa.Column('new_state', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['qap_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_qap_appract_entity_created', 'qap_approval_actions', ['entity_type', 'entity_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_qap_approval_actions_entity_id'), 'qap_approval_actions', ['entity_id'], unique=False)
    op.create_table('qap_audit_logs',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.Column('event_type', sa.String(length=40), nullable=False),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('outcome', sa.String(length=20), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('actor_username', sa.String(length=150), nullable=True),
    sa.Column('actor_name', sa.String(length=150), nullable=True),
    sa.Column('actor_roles', sa.String(length=500), nullable=True),
    sa.Column('method', sa.String(length=10), nullable=True),
    sa.Column('path', sa.String(length=500), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('target_type', sa.String(length=64), nullable=True),
    sa.Column('target_id', sa.String(length=100), nullable=True),
    sa.Column('target_name', sa.String(length=255), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['qap_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_qap_audit_actor_created', 'qap_audit_logs', ['actor_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_qap_audit_logs_action'), 'qap_audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_qap_audit_logs_actor_username'), 'qap_audit_logs', ['actor_username'], unique=False)
    op.create_index(op.f('ix_qap_audit_logs_created_at'), 'qap_audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_qap_audit_logs_event_type'), 'qap_audit_logs', ['event_type'], unique=False)
    op.create_index(op.f('ix_qap_audit_logs_outcome'), 'qap_audit_logs', ['outcome'], unique=False)
    op.create_index(op.f('ix_qap_audit_logs_path'), 'qap_audit_logs', ['path'], unique=False)
    op.create_index(op.f('ix_qap_audit_logs_request_id'), 'qap_audit_logs', ['request_id'], unique=False)
    op.create_index('ix_qap_audit_target', 'qap_audit_logs', ['target_type', 'target_id'], unique=False)
    op.create_table('qap_dast_requests',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.Column('request_id', sa.String(length=40), nullable=True),
    sa.Column('risk_category', sa.String(length=16), nullable=True),
    sa.Column('priority', sa.String(length=16), nullable=True),
    sa.Column('supporting_docs_path', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('needs_dept_head_reapproval', sa.Boolean(), nullable=True),
    sa.Column('requester_id', sa.Integer(), nullable=True),
    sa.Column('security_lead_id', sa.Integer(), nullable=True),
    sa.Column('security_analyst_id', sa.Integer(), nullable=True),
    sa.Column('report_path', sa.String(length=255), nullable=True),
    sa.Column('qa_request_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['qa_request_id'], ['qap_requests.id'], ),
    sa.ForeignKeyConstraint(['requester_id'], ['qap_users.id'], ),
    sa.ForeignKeyConstraint(['security_analyst_id'], ['qap_users.id'], ),
    sa.ForeignKeyConstraint(['security_lead_id'], ['qap_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_id')
    )
    op.create_index('ix_qap_dast_qa_req', 'qap_dast_requests', ['qa_request_id'], unique=False)
    op.create_index('ix_qap_dast_status_created', 'qap_dast_requests', ['status', 'created_at'], unique=False)
    op.create_table('qap_module_documents',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.Column('module', sa.String(length=20), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('stored_path', sa.String(length=500), nullable=False),
    sa.Column('content_type', sa.String(length=150), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['qap_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_qap_moddocs_req_uploaded', 'qap_module_documents', ['module', 'request_id', 'uploaded_at'], unique=False)
    op.create_index(op.f('ix_qap_module_documents_request_id'), 'qap_module_documents', ['request_id'], unique=False)
    op.create_table('qap_performance_requests',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.Column('request_id', sa.String(length=40), nullable=True),
    sa.Column('application_name', sa.String(length=150), nullable=False),
    sa.Column('epic_number', sa.String(length=150), nullable=True),
    sa.Column('cr_number', sa.String(length=64), nullable=True),
    sa.Column('tool_used', sa.String(length=150), nullable=True),
    sa.Column('target_load', sa.String(length=150), nullable=True),
    sa.Column('environment', sa.String(length=32), nullable=True),
    sa.Column('risk_category', sa.String(length=16), nullable=True),
    sa.Column('priority', sa.String(length=16), nullable=True),
    sa.Column('request_type', sa.String(length=120), nullable=True),
    sa.Column('change_type', sa.String(length=32), nullable=True),
    sa.Column('vendor_si_partner', sa.String(length=150), nullable=True),
    sa.Column('technology_stack', sa.String(length=150), nullable=True),
    sa.Column('release_version', sa.String(length=64), nullable=True),
    sa.Column('build_number', sa.String(length=64), nullable=True),
    sa.Column('hash_value', sa.String(length=255), nullable=True),
    sa.Column('target_promotion_environment', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('needs_dept_head_reapproval', sa.Boolean(), nullable=True),
    sa.Column('requester_id', sa.Integer(), nullable=True),
    sa.Column('engineer_id', sa.Integer(), nullable=True),
    sa.Column('assigned_tester_ids', sa.String(length=255), nullable=True),
    sa.Column('report_path', sa.String(length=255), nullable=True),
    sa.Column('qa_request_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['engineer_id'], ['qap_users.id'], ),
    sa.ForeignKeyConstraint(['qa_request_id'], ['qap_requests.id'], ),
    sa.ForeignKeyConstraint(['requester_id'], ['qap_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_id')
    )
    op.create_index('ix_qap_perf_qa_req', 'qap_performance_requests', ['qa_request_id'], unique=False)
    op.create_index('ix_qap_perf_status_created', 'qap_performance_requests', ['status', 'created_at'], unique=False)
    op.create_table('qap_request_documents',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.Column('qa_request_id', sa.Integer(), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('stored_path', sa.String(length=500), nullable=False),
    sa.Column('content_type', sa.String(length=150), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['qa_request_id'], ['qap_requests.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['qap_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('qap_sast_requests',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.Column('request_id', sa.String(length=40), nullable=True),
    sa.Column('application_name', sa.String(length=150), nullable=False),
    sa.Column('epic_number', sa.String(length=150), nullable=True),
    sa.Column('cr_number', sa.String(length=64), nullable=True),
    sa.Column('risk_category', sa.String(length=16), nullable=True),
    sa.Column('priority', sa.String(length=16), nullable=True),
    sa.Column('source_code_path', sa.String(length=255), nullable=True),
    sa.Column('hash_value', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('needs_dept_head_reapproval', sa.Boolean(), nullable=True),
    sa.Column('requester_id', sa.Integer(), nullable=True),
    sa.Column('security_lead_id', sa.Integer(), nullable=True),
    sa.Column('security_analyst_id', sa.Integer(), nullable=True),
    sa.Column('report_path', sa.String(length=255), nullable=True),
    sa.Column('qa_request_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['qa_request_id'], ['qap_requests.id'], ),
    sa.ForeignKeyConstraint(['requester_id'], ['qap_users.id'], ),
    sa.ForeignKeyConstraint(['security_analyst_id'], ['qap_users.id'], ),
    sa.ForeignKeyConstraint(['security_lead_id'], ['qap_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_id')
    )
    op.create_index('ix_qap_sast_qa_req', 'qap_sast_requests', ['qa_request_id'], unique=False)
    op.create_index('ix_qap_sast_status_created', 'qap_sast_requests', ['status', 'created_at'], unique=False)
    op.create_table('qap_security_scan_results',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.Column('request_type', sa.String(length=8), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('application_name', sa.String(length=150), nullable=False),
    sa.Column('application_version', sa.String(length=100), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('provider_version_id', sa.String(length=100), nullable=False),
    sa.Column('critical_count', sa.Integer(), nullable=False),
    sa.Column('high_count', sa.Integer(), nullable=False),
    sa.Column('medium_count', sa.Integer(), nullable=False),
    sa.Column('low_count', sa.Integer(), nullable=False),
    sa.Column('total_count', sa.Integer(), nullable=False),
    sa.Column('audit_url', sa.String(length=1000), nullable=True),
    sa.Column('filters_json', sa.Text(), nullable=True),
    sa.Column('imported_by_id', sa.Integer(), nullable=True),
    sa.Column('imported_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['imported_by_id'], ['qap_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qap_security_scan_results_request_id'), 'qap_security_scan_results', ['request_id'], unique=False)
    op.create_index(op.f('ix_qap_security_scan_results_request_type'), 'qap_security_scan_results', ['request_type'], unique=False)
    op.create_table('qap_signoffs',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.Column('certificate_id', sa.String(length=40), nullable=True),
    sa.Column('certificate_date', sa.Date(), nullable=True),
    sa.Column('certificate_type', sa.String(length=32), nullable=True),
    sa.Column('testing_type', sa.String(length=16), nullable=True),
    sa.Column('testing_request_id', sa.String(length=40), nullable=True),
    sa.Column('change_request_ids', sa.String(length=255), nullable=True),
    sa.Column('application_name', sa.String(length=150), nullable=False),
    sa.Column('application_owner', sa.String(length=150), nullable=True),
    sa.Column('department', sa.String(length=150), nullable=True),
    sa.Column('vendor_si_partner', sa.String(length=150), nullable=True),
    sa.Column('technology_stack', sa.String(length=150), nullable=True),
    sa.Column('risk_tier', sa.String(length=32), nullable=True),
    sa.Column('release_version', sa.String(length=64), nullable=True),
    sa.Column('build_number', sa.String(length=64), nullable=True),
    sa.Column('environment_tested', sa.String(length=32), nullable=True),
    sa.Column('target_promotion_environment', sa.String(length=32), nullable=True),
    sa.Column('validity_from', sa.Date(), nullable=True),
    sa.Column('validity_to', sa.Date(), nullable=True),
    sa.Column('exit_criteria_notes', sa.Text(), nullable=True),
    sa.Column('open_defect_summary', sa.Text(), nullable=True),
    sa.Column('residual_risk_notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('requester_id', sa.Integer(), nullable=True),
    sa.Column('reviewed_by_id', sa.Integer(), nullable=True),
    sa.Column('approved_by_id', sa.Integer(), nullable=True),
    sa.Column('issued_by_id', sa.Integer(), nullable=True),
    sa.Column('signed_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by_id'], ['qap_users.id'], ),
    sa.ForeignKeyConstraint(['issued_by_id'], ['qap_users.id'], ),
    sa.ForeignKeyConstraint(['requester_id'], ['qap_users.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['qap_users.id'], ),
    sa.ForeignKeyConstraint(['signed_by_id'], ['qap_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('certificate_id')
    )
    op.create_index('ix_qap_signoff_testreq', 'qap_signoffs', ['testing_request_id'], unique=False)
    op.create_table('qap_test_case_tags',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.Column('test_case_id', sa.Integer(), nullable=False),
    sa.Column('tag', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['test_case_id'], ['qap_test_cases.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('test_case_id', 'tag', name='uq_qap_test_case_tag')
    )
    op.create_index(op.f('ix_qap_test_case_tags_tag'), 'qap_test_case_tags', ['tag'], unique=False)
    op.create_index(op.f('ix_qap_test_case_tags_test_case_id'), 'qap_test_case_tags', ['test_case_id'], unique=False)
    op.create_table('qap_test_case_version_steps',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('step_no', sa.Integer(), nullable=False),
    sa.Column('step_text', sa.Text(), nullable=True),
    sa.Column('expected_result', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['version_id'], ['qap_test_case_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version_id', 'step_no', name='uq_qap_tcvs_version_step')
    )
    op.create_index(op.f('ix_qap_test_case_version_steps_version_id'), 'qap_test_case_version_steps', ['version_id'], unique=False)
    op.create_table('qap_test_projects',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.Column('project_key', sa.String(length=40), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('application_master_id', sa.Integer(), nullable=True),
    sa.Column('department', sa.String(length=150), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('pending_is_active', sa.Boolean(), nullable=True),
    sa.Column('pending_requested_by_id', sa.Integer(), nullable=True),
    sa.Column('pending_requested_at', sa.DateTime(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=True),
    sa.Column('archived_by_id', sa.Integer(), nullable=True),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.Column('archived_reason', sa.Text(), nullable=True),
    sa.Column('default_reviewer_id', sa.Integer(), nullable=True),
    sa.Column('default_qa_lead_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['application_master_id'], ['qap_application_master.id'], ),
    sa.ForeignKeyConstraint(['archived_by_id'], ['qap_users.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['qap_users.id'], ),
    sa.ForeignKeyConstraint(['default_qa_lead_id'], ['qap_users.id'], ),
    sa.ForeignKeyConstraint(['default_reviewer_id'], ['qap_users.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['qap_users.id'], ),
    sa.ForeignKeyConstraint(['pending_requested_by_id'], ['qap_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_key')
    )
    op.create_index('ix_qap_proj_dept', 'qap_test_projects', ['department'], unique=False)
    op.create_table('qap_test_steps',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.Column('test_case_id', sa.Integer(), nullable=False),
    sa.Column('step_no', sa.Integer(), nullable=False),
    sa.Column('step_text', sa.Text(), nullable=True),
    sa.Column('expected_result', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['test_case_id'], ['qap_test_cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('qap_user_departments',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('department', sa.String(length=150), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['qap_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'department', name='uq_qap_user_departments')
    )
    op.create_table('qap_user_roles',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['qap_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'role', name='uq_qap_user_roles')
    )
    op.create_table('qap_dast_checklist_items',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.Column('dast_request_id', sa.Integer(), nullable=True),
    sa.Column('item', sa.String(length=255), nullable=False),
    sa.Column('owner', sa.String(length=150), nullable=True),
    sa.Column('is_mandatory', sa.Boolean(), nullable=True),
    sa.Column('requester_checked', sa.Boolean(), nullable=True),
    sa.Column('is_complete', sa.Boolean(), nullable=True),
    sa.Column('approved_by_id', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by_id'], ['qap_users.id'], ),
    sa.ForeignKeyConstraint(['dast_request_id'], ['qap_dast_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('qap_dast_findings',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.Column('dast_request_id', sa.Integer(), nullable=True),
    sa.Column('issue_id', sa.String(length=64), nullable=True),
    sa.Column('severity', sa.String(length=16), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['dast_request_id'], ['qap_dast_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('qap_dast_targets',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.Column('dast_request_id', sa.Integer(), nullable=False),
    sa.Column('application_url', sa.String(length=2000), nullable=False),
    sa.Column('environment', sa.String(length=500), nullable=True),
    sa.Column('authentication_required', sa.String(length=16), nullable=True),
    sa.Column('test_credentials', sa.String(length=2000), nullable=True),
    sa.ForeignKeyConstraint(['dast_request_id'], ['qap_dast_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('qap_functional_requests',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.Column('request_id', sa.String(length=40), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('needs_dept_head_reapproval', sa.Boolean(), nullable=True),
    sa.Column('priority', sa.String(length=16), nullable=True),
    sa.Column('risk_rating', sa.String(length=16), nullable=True),
    sa.Column('requester_id', sa.Integer(), nullable=True),
    sa.Column('department_head_id', sa.Integer(), nullable=True),
    sa.Column('qa_lead_id', sa.Integer(), nullable=True),
    sa.Column('assigned_tester_ids', sa.String(length=255), nullable=True),
    sa.Column('signoff_id', sa.Integer(), nullable=True),
    sa.Column('qa_request_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['department_head_id'], ['qap_users.id'], ),
    sa.ForeignKeyConstraint(['qa_lead_id'], ['qap_users.id'], ),
    sa.ForeignKeyConstraint(['qa_request_id'], ['qap_requests.id'], ),
    sa.ForeignKeyConstraint(['requester_id'], ['qap_users.id'], ),
    sa.ForeignKeyConstraint(['signoff_id'], ['qap_signoffs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_id')
    )
    op.create_index('ix_qap_func_qa_req', 'qap_functional_requests', ['qa_request_id'], unique=False)
    op.create_index('ix_qap_func_status_created', 'qap_functional_requests', ['status', 'created_at'], unique=False)
    op.create_table('qap_performance_checklist_items',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.Column('performance_request_id', sa.Integer(), nullable=True),
    sa.Column('item', sa.String(length=255), nullable=False),
    sa.Column('data_required', sa.String(length=255), nullable=True),
    sa.Column('is_mandatory', sa.Boolean(), nullable=True),
    sa.Column('requester_checked', sa.Boolean(), nullable=True),
    sa.Column('is_complete', sa.Boolean(), nullable=True),
    sa.Column('approved_by_id', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by_id'], ['qap_users.id'], ),
    sa.ForeignKeyConstraint(['performance_request_id'], ['qap_performance_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('qap_sast_checklist_items',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.Column('sast_request_id', sa.Integer(), nullable=True),
    sa.Column('item', sa.String(length=255), nullable=False),
    sa.Column('owner', sa.String(length=150), nullable=True),
    sa.Column('is_mandatory', sa.Boolean(), nullable=True),
    sa.Column('requester_checked', sa.Boolean(), nullable=True),
    sa.Column('is_complete', sa.Boolean(), nullable=True),
    sa.Column('approved_by_id', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by_id'], ['qap_users.id'], ),
    sa.ForeignKeyConstraint(['sast_request_id'], ['qap_sast_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('qap_sast_components',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.Column('sast_request_id', sa.Integer(), nullable=False),
    sa.Column('repository_url', sa.String(length=1000), nullable=True),
    sa.Column('git_branch', sa.String(length=500), nullable=True),
    sa.Column('commit_id', sa.String(length=500), nullable=True),
    sa.Column('technology_stack', sa.String(length=500), nullable=True),
    sa.Column('build_number', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['sast_request_id'], ['qap_sast_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('qap_sast_findings',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.Column('sast_request_id', sa.Integer(), nullable=True),
    sa.Column('issue_id', sa.String(length=64), nullable=True),
    sa.Column('severity', sa.String(length=16), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['sast_request_id'], ['qap_sast_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('qap_suppression_requests',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.Column('suppression_id', sa.String(length=40), nullable=True),
    sa.Column('application_name', sa.String(length=150), nullable=False),
    sa.Column('scan_type', sa.String(length=16), nullable=True),
    sa.Column('department', sa.String(length=150), nullable=True),
    sa.Column('application_owner', sa.String(length=150), nullable=True),
    sa.Column('sast_request_id', sa.Integer(), nullable=True),
    sa.Column('dast_request_id', sa.Integer(), nullable=True),
    sa.Column('risk_assessment', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('app_owner_decision', sa.String(length=16), nullable=True),
    sa.Column('app_owner_id', sa.Integer(), nullable=True),
    sa.Column('app_owner_decided_at', sa.DateTime(), nullable=True),
    sa.Column('sm_decision', sa.String(length=16), nullable=True),
    sa.Column('sm_id', sa.Integer(), nullable=True),
    sa.Column('sm_decided_at', sa.DateTime(), nullable=True),
    sa.Column('dept_head_decision', sa.String(length=16), nullable=True),
    sa.Column('dept_head_id', sa.Integer(), nullable=True),
    sa.Column('dept_head_decided_at', sa.DateTime(), nullable=True),
    sa.Column('security_decision', sa.String(length=16), nullable=True),
    sa.Column('security_id', sa.Integer(), nullable=True),
    sa.Column('security_decided_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['app_owner_id'], ['qap_users.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['qap_users.id'], ),
    sa.ForeignKeyConstraint(['dast_request_id'], ['qap_dast_requests.id'], ),
    sa.ForeignKeyConstraint(['dept_head_id'], ['qap_users.id'], ),
    sa.ForeignKeyConstraint(['sast_request_id'], ['qap_sast_requests.id'], ),
    sa.ForeignKeyConstraint(['security_id'], ['qap_users.id'], ),
    sa.ForeignKeyConstraint(['sm_id'], ['qap_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('suppression_id')
    )
    op.create_index('ix_qap_sup_dept', 'qap_suppression_requests', ['department'], unique=False)
    op.create_table('qap_test_cycles',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.Column('cycle_key', sa.String(length=40), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('cycle_type', sa.String(length=30), nullable=True),
    sa.Column('environment', sa.String(length=60), nullable=True),
    sa.Column('build', sa.String(length=100), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['qap_users.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['qap_users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['qap_test_projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cycle_key')
    )
    op.create_index('ix_qap_cyc_proj_status_created', 'qap_test_cycles', ['project_id', 'status', 'created_at'], unique=False)
    op.create_table('qap_test_folders',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['qap_users.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['qap_test_folders.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['qap_test_projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qap_test_folders_project_id'), 'qap_test_folders', ['project_id'], unique=False)
    op.create_table('qap_test_project_members',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('project_role', sa.String(length=30), nullable=False),
    sa.Column('added_by_id', sa.Integer(), nullable=True),
    sa.Column('added_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['added_by_id'], ['qap_users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['qap_test_projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['qap_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'user_id', name='uq_qap_tpm_project_user')
    )
    op.create_index(op.f('ix_qap_test_project_members_project_id'), 'qap_test_project_members', ['project_id'], unique=False)
    op.create_index(op.f('ix_qap_test_project_members_user_id'), 'qap_test_project_members', ['user_id'], unique=False)
    op.create_table('qap_test_project_view_grants',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('department', sa.String(length=150), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('granted_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['granted_by_id'], ['qap_users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['qap_test_projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['qap_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'department', name='uq_qap_tpvg_project_department'),
    sa.UniqueConstraint('project_id', 'user_id', name='uq_qap_tpvg_project_user')
    )
    op.create_index(op.f('ix_qap_test_project_view_grants_project_id'), 'qap_test_project_view_grants', ['project_id'], unique=False)
    op.create_index(op.f('ix_qap_test_project_view_grants_user_id'), 'qap_test_project_view_grants', ['user_id'], unique=False)
    op.create_table('qap_readiness_checklist_items',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.Column('functional_request_id', sa.Integer(), nullable=True),
    sa.Column('item', sa.String(length=255), nullable=False),
    sa.Column('owner', sa.String(length=150), nullable=True),
    sa.Column('is_mandatory', sa.Boolean(), nullable=True),
    sa.Column('requester_checked', sa.Boolean(), nullable=True),
    sa.Column('is_complete', sa.Boolean(), nullable=True),
    sa.Column('approved_by_id', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by_id'], ['qap_users.id'], ),
    sa.ForeignKeyConstraint(['functional_request_id'], ['qap_functional_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_qap_readiness_func_req', 'qap_readiness_checklist_items', ['functional_request_id'], unique=False)
    op.create_table('qap_suppression_items',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.Column('suppression_request_id', sa.Integer(), nullable=True),
    sa.Column('issue_id', sa.String(length=64), nullable=True),
    sa.Column('severity', sa.String(length=16), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('justification', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['suppression_request_id'], ['qap_suppression_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('qap_test_cycle_child_links',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.Column('cycle_id', sa.Integer(), nullable=False),
    sa.Column('child_type', sa.String(length=20), nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=False),
    sa.Column('child_key', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['cycle_id'], ['qap_test_cycles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cycle_id')
    )
    op.create_index(op.f('ix_qap_test_cycle_child_links_child_id'), 'qap_test_cycle_child_links', ['child_id'], unique=False)
    op.create_index(op.f('ix_qap_test_cycle_child_links_child_key'), 'qap_test_cycle_child_links', ['child_key'], unique=False)
    op.create_table('qap_test_executions',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.Column('cycle_id', sa.Integer(), nullable=False),
    sa.Column('test_case_id', sa.Integer(), nullable=False),
    sa.Column('pinned_version_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('actual_result', sa.Text(), nullable=True),
    sa.Column('test_run_artifacts', sa.String(length=255), nullable=True),
    sa.Column('defect_id', sa.String(length=60), nullable=True),
    sa.Column('assigned_to_id', sa.Integer(), nullable=True),
    sa.Column('assigned_by_id', sa.Integer(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.Column('executed_by_id', sa.Integer(), nullable=True),
    sa.Column('executed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('run_version', sa.Integer(), nullable=False),
    sa.Column('added_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['added_by_id'], ['qap_users.id'], ),
    sa.ForeignKeyConstraint(['assigned_by_id'], ['qap_users.id'], ),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['qap_users.id'], ),
    sa.ForeignKeyConstraint(['cycle_id'], ['qap_test_cycles.id'], ),
    sa.ForeignKeyConstraint(['executed_by_id'], ['qap_users.id'], ),
    sa.ForeignKeyConstraint(['pinned_version_id'], ['qap_test_case_versions.id'], ),
    sa.ForeignKeyConstraint(['test_case_id'], ['qap_test_cases.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cycle_id', 'test_case_id', name='uq_qap_test_exec_cycle_case')
    )
    op.create_index(op.f('ix_qap_test_executions_assigned_to_id'), 'qap_test_executions', ['assigned_to_id'], unique=False)
    op.create_table('qap_defects',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.Column('defect_key', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('qa_request_id', sa.Integer(), nullable=False),
    sa.Column('cycle_id', sa.Integer(), nullable=True),
    sa.Column('primary_test_case_id', sa.Integer(), nullable=True),
    sa.Column('execution_id', sa.Integer(), nullable=True),
    sa.Column('application_name', sa.String(length=150), nullable=False),
    sa.Column('module_feature', sa.String(length=150), nullable=False),
    sa.Column('environment', sa.String(length=60), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('steps_to_reproduce', sa.Text(), nullable=False),
    sa.Column('expected_result', sa.Text(), nullable=False),
    sa.Column('actual_result', sa.Text(), nullable=False),
    sa.Column('reporter_id', sa.Integer(), nullable=False),
    sa.Column('reported_at', sa.DateTime(), nullable=False),
    sa.Column('assignee_id', sa.Integer(), nullable=True),
    sa.Column('assigned_team', sa.String(length=150), nullable=True),
    sa.Column('assigned_by_id', sa.Integer(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.Column('assignment_remarks', sa.Text(), nullable=True),
    sa.Column('retest_tester_id', sa.Integer(), nullable=True),
    sa.Column('device_details', sa.String(length=255), nullable=True),
    sa.Column('build_version', sa.String(length=100), nullable=True),
    sa.Column('api_endpoint', sa.String(length=500), nullable=True),
    sa.Column('request_response_details', sa.Text(), nullable=True),
    sa.Column('log_details', sa.Text(), nullable=True),
    sa.Column('related_cr_number', sa.String(length=64), nullable=True),
    sa.Column('external_defect_id', sa.String(length=100), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('labels', sa.String(length=500), nullable=True),
    sa.Column('resolution_type', sa.String(length=60), nullable=True),
    sa.Column('resolution_summary', sa.Text(), nullable=True),
    sa.Column('root_cause', sa.Text(), nullable=True),
    sa.Column('fix_details', sa.Text(), nullable=True),
    sa.Column('fixed_build_version', sa.String(length=100), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('retest_result', sa.String(length=20), nullable=True),
    sa.Column('retest_at', sa.DateTime(), nullable=True),
    sa.Column('tested_build_version', sa.String(length=100), nullable=True),
    sa.Column('retest_actual_result', sa.Text(), nullable=True),
    sa.Column('retest_remarks', sa.Text(), nullable=True),
    sa.Column('reopen_reason', sa.Text(), nullable=True),
    sa.Column('reopen_count', sa.Integer(), nullable=False),
    sa.Column('deferral_reason', sa.Text(), nullable=True),
    sa.Column('deferral_approved_by', sa.String(length=150), nullable=True),
    sa.Column('target_release', sa.String(length=100), nullable=True),
    sa.Column('expected_resolution_date', sa.Date(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('duplicate_of_id', sa.Integer(), nullable=True),
    sa.Column('not_a_defect_reason', sa.Text(), nullable=True),
    sa.Column('closure_remarks', sa.Text(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by_id'], ['qap_users.id'], ),
    sa.ForeignKeyConstraint(['assignee_id'], ['qap_users.id'], ),
    sa.ForeignKeyConstraint(['cycle_id'], ['qap_test_cycles.id'], ),
    sa.ForeignKeyConstraint(['duplicate_of_id'], ['qap_defects.id'], ),
    sa.ForeignKeyConstraint(['execution_id'], ['qap_test_executions.id'], ),
    sa.ForeignKeyConstraint(['primary_test_case_id'], ['qap_test_cases.id'], ),
    sa.ForeignKeyConstraint(['qa_request_id'], ['qap_requests.id'], ),
    sa.ForeignKeyConstraint(['reporter_id'], ['qap_users.id'], ),
    sa.ForeignKeyConstraint(['retest_tester_id'], ['qap_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_qap_defects_assignee_upd', 'qap_defects', ['assignee_id', 'status', 'updated_at'], unique=False)
    op.create_index(op.f('ix_qap_defects_cycle_id'), 'qap_defects', ['cycle_id'], unique=False)
    op.create_index(op.f('ix_qap_defects_defect_key'), 'qap_defects', ['defect_key'], unique=True)
    op.create_index(op.f('ix_qap_defects_execution_id'), 'qap_defects', ['execution_id'], unique=False)
    op.create_index(op.f('ix_qap_defects_primary_test_case_id'), 'qap_defects', ['primary_test_case_id'], unique=False)
    op.create_index(op.f('ix_qap_defects_priority'), 'qap_defects', ['priority'], unique=False)
    op.create_index(op.f('ix_qap_defects_qa_request_id'), 'qap_defects', ['qa_request_id'], unique=False)
    op.create_index(op.f('ix_qap_defects_reporter_id'), 'qap_defects', ['reporter_id'], unique=False)
    op.create_index(op.f('ix_qap_defects_severity'), 'qap_defects', ['severity'], unique=False)
    op.create_index(op.f('ix_qap_defects_status'), 'qap_defects', ['status'], unique=False)
    op.create_table('qap_test_execution_runs',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.Column('execution_id', sa.Integer(), nullable=False),
    sa.Column('attempt_no', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('actual_result', sa.Text(), nullable=True),
    sa.Column('test_run_artifacts', sa.String(length=255), nullable=True),
    sa.Column('defect_id', sa.String(length=60), nullable=True),
    sa.Column('executed_by_id', sa.Integer(), nullable=True),
    sa.Column('executed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['executed_by_id'], ['qap_users.id'], ),
    sa.ForeignKeyConstraint(['execution_id'], ['qap_test_executions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('execution_id', 'attempt_no', name='uq_qap_test_run_attempt')
    )
    op.create_table('qap_defect_case_links',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.Column('defect_id', sa.Integer(), nullable=False),
    sa.Column('test_case_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['defect_id'], ['qap_defects.id'], ),
    sa.ForeignKeyConstraint(['test_case_id'], ['qap_test_cases.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('defect_id', 'test_case_id', name='uq_qap_def_case')
    )
    op.create_index(op.f('ix_qap_defect_case_links_defect_id'), 'qap_defect_case_links', ['defect_id'], unique=False)
    op.create_index(op.f('ix_qap_defect_case_links_test_case_id'), 'qap_defect_case_links', ['test_case_id'], unique=False)
    op.create_table('qap_test_run_defects',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('defect_key', sa.String(length=100), nullable=False),
    sa.Column('defect_url', sa.String(length=500), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('defect_status', sa.String(length=40), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('linked_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['linked_by_id'], ['qap_users.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['qap_test_execution_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'defect_key', name='uq_qap_run_defect_key')
    )
    op.create_index(op.f('ix_qap_test_run_defects_run_id'), 'qap_test_run_defects', ['run_id'], unique=False)
    op.create_foreign_key(
        'fk_qap_app_master_qa_req', 'qap_application_master', 'qap_requests',
        ['qa_request_id'], ['id'],
    )
    op.create_foreign_key(
        'fk_qap_tcv_test_case', 'qap_test_case_versions', 'qap_test_cases',
        ['test_case_id'], ['id'],
    )
    op.create_foreign_key(
        'fk_qap_tc_project', 'qap_test_cases', 'qap_test_projects',
        ['project_id'], ['id'],
    )
    op.create_foreign_key(
        'fk_qap_tc_folder', 'qap_test_cases', 'qap_test_folders',
        ['folder_id'], ['id'],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_qap_tc_folder', 'qap_test_cases', type_='foreignkey')
    op.drop_constraint('fk_qap_tc_project', 'qap_test_cases', type_='foreignkey')
    op.drop_constraint('fk_qap_tcv_test_case', 'qap_test_case_versions', type_='foreignkey')
    op.drop_constraint('fk_qap_app_master_qa_req', 'qap_application_master', type_='foreignkey')
    op.drop_index(op.f('ix_qap_test_run_defects_run_id'), table_name='qap_test_run_defects')
    op.drop_table('qap_test_run_defects')
    op.drop_index(op.f('ix_qap_defect_case_links_test_case_id'), table_name='qap_defect_case_links')
    op.drop_index(op.f('ix_qap_defect_case_links_defect_id'), table_name='qap_defect_case_links')
    op.drop_table('qap_defect_case_links')
    op.drop_table('qap_test_execution_runs')
    op.drop_index(op.f('ix_qap_defects_status'), table_name='qap_defects')
    op.drop_index(op.f('ix_qap_defects_severity'), table_name='qap_defects')
    op.drop_index(op.f('ix_qap_defects_reporter_id'), table_name='qap_defects')
    op.drop_index(op.f('ix_qap_defects_qa_request_id'), table_name='qap_defects')
    op.drop_index(op.f('ix_qap_defects_priority'), table_name='qap_defects')
    op.drop_index(op.f('ix_qap_defects_primary_test_case_id'), table_name='qap_defects')
    op.drop_index(op.f('ix_qap_defects_execution_id'), table_name='qap_defects')
    op.drop_index(op.f('ix_qap_defects_defect_key'), table_name='qap_defects')
    op.drop_index(op.f('ix_qap_defects_cycle_id'), table_name='qap_defects')
    op.drop_index('ix_qap_defects_assignee_upd', table_name='qap_defects')
    op.drop_table('qap_defects')
    op.drop_index(op.f('ix_qap_test_executions_assigned_to_id'), table_name='qap_test_executions')
    op.drop_table('qap_test_executions')
    op.drop_index(op.f('ix_qap_test_cycle_child_links_child_key'), table_name='qap_test_cycle_child_links')
    op.drop_index(op.f('ix_qap_test_cycle_child_links_child_id'), table_name='qap_test_cycle_child_links')
    op.drop_table('qap_test_cycle_child_links')
    op.drop_table('qap_suppression_items')
    op.drop_index('ix_qap_readiness_func_req', table_name='qap_readiness_checklist_items')
    op.drop_table('qap_readiness_checklist_items')
    op.drop_index(op.f('ix_qap_test_project_view_grants_user_id'), table_name='qap_test_project_view_grants')
    op.drop_index(op.f('ix_qap_test_project_view_grants_project_id'), table_name='qap_test_project_view_grants')
    op.drop_table('qap_test_project_view_grants')
    op.drop_index(op.f('ix_qap_test_project_members_user_id'), table_name='qap_test_project_members')
    op.drop_index(op.f('ix_qap_test_project_members_project_id'), table_name='qap_test_project_members')
    op.drop_table('qap_test_project_members')
    op.drop_index(op.f('ix_qap_test_folders_project_id'), table_name='qap_test_folders')
    op.drop_table('qap_test_folders')
    op.drop_index('ix_qap_cyc_proj_status_created', table_name='qap_test_cycles')
    op.drop_table('qap_test_cycles')
    op.drop_index('ix_qap_sup_dept', table_name='qap_suppression_requests')
    op.drop_table('qap_suppression_requests')
    op.drop_table('qap_sast_findings')
    op.drop_table('qap_sast_components')
    op.drop_table('qap_sast_checklist_items')
    op.drop_table('qap_performance_checklist_items')
    op.drop_index('ix_qap_func_status_created', table_name='qap_functional_requests')
    op.drop_index('ix_qap_func_qa_req', table_name='qap_functional_requests')
    op.drop_table('qap_functional_requests')
    op.drop_table('qap_dast_targets')
    op.drop_table('qap_dast_findings')
    op.drop_table('qap_dast_checklist_items')
    op.drop_table('qap_user_roles')
    op.drop_table('qap_user_departments')
    op.drop_table('qap_test_steps')
    op.drop_index('ix_qap_proj_dept', table_name='qap_test_projects')
    op.drop_table('qap_test_projects')
    op.drop_index(op.f('ix_qap_test_case_version_steps_version_id'), table_name='qap_test_case_version_steps')
    op.drop_table('qap_test_case_version_steps')
    op.drop_index(op.f('ix_qap_test_case_tags_test_case_id'), table_name='qap_test_case_tags')
    op.drop_index(op.f('ix_qap_test_case_tags_tag'), table_name='qap_test_case_tags')
    op.drop_table('qap_test_case_tags')
    op.drop_index('ix_qap_signoff_testreq', table_name='qap_signoffs')
    op.drop_table('qap_signoffs')
    op.drop_index(op.f('ix_qap_security_scan_results_request_type'), table_name='qap_security_scan_results')
    op.drop_index(op.f('ix_qap_security_scan_results_request_id'), table_name='qap_security_scan_results')
    op.drop_table('qap_security_scan_results')
    op.drop_index('ix_qap_sast_status_created', table_name='qap_sast_requests')
    op.drop_index('ix_qap_sast_qa_req', table_name='qap_sast_requests')
    op.drop_table('qap_sast_requests')
    op.drop_table('qap_request_documents')
    op.drop_index('ix_qap_perf_status_created', table_name='qap_performance_requests')
    op.drop_index('ix_qap_perf_qa_req', table_name='qap_performance_requests')
    op.drop_table('qap_performance_requests')
    op.drop_index(op.f('ix_qap_module_documents_request_id'), table_name='qap_module_documents')
    op.drop_index('ix_qap_moddocs_req_uploaded', table_name='qap_module_documents')
    op.drop_table('qap_module_documents')
    op.drop_index('ix_qap_dast_status_created', table_name='qap_dast_requests')
    op.drop_index('ix_qap_dast_qa_req', table_name='qap_dast_requests')
    op.drop_table('qap_dast_requests')
    op.drop_index('ix_qap_audit_target', table_name='qap_audit_logs')
    op.drop_index(op.f('ix_qap_audit_logs_request_id'), table_name='qap_audit_logs')
    op.drop_index(op.f('ix_qap_audit_logs_path'), table_name='qap_audit_logs')
    op.drop_index(op.f('ix_qap_audit_logs_outcome'), table_name='qap_audit_logs')
    op.drop_index(op.f('ix_qap_audit_logs_event_type'), table_name='qap_audit_logs')
    op.drop_index(op.f('ix_qap_audit_logs_created_at'), table_name='qap_audit_logs')
    op.drop_index(op.f('ix_qap_audit_logs_actor_username'), table_name='qap_audit_logs')
    op.drop_index(op.f('ix_qap_audit_logs_action'), table_name='qap_audit_logs')
    op.drop_index('ix_qap_audit_actor_created', table_name='qap_audit_logs')
    op.drop_table('qap_audit_logs')
    op.drop_index(op.f('ix_qap_approval_actions_entity_id'), table_name='qap_approval_actions')
    op.drop_index('ix_qap_appract_entity_created', table_name='qap_approval_actions')
    op.drop_table('qap_approval_actions')
    op.drop_index('ix_qap_tc_proj_folder_created', table_name='qap_test_cases')
    op.drop_index('ix_qap_tc_proj_deleted_created', table_name='qap_test_cases')
    op.drop_table('qap_test_cases')
    op.drop_index(op.f('ix_qap_test_case_versions_test_case_id'), table_name='qap_test_case_versions')
    op.drop_table('qap_test_case_versions')
    op.drop_table('qap_system_settings')
    op.drop_index(op.f('ix_qap_requests_status'), table_name='qap_requests')
    op.drop_index('ix_qap_req_dept_status_created', table_name='qap_requests')
    op.drop_table('qap_requests')
    op.drop_table('qap_id_counters')
    op.drop_table('qap_departments')
    op.drop_table('qap_checklist_template_items')
    op.drop_index(op.f('ix_qap_application_master_status'), table_name='qap_application_master')
    op.drop_table('qap_application_master')
    op.drop_table('qap_users')
    # ### end Alembic commands ###
