"""
Shared PDF builder for a single request's full "detail certificate" export --
every field plus its complete approval/workflow history (who acted, what they
decided, and when), as one downloadable PDF. This is a different shape of
export than routers/export.py's Download & Export Centre: that one streams
many rows of one report/screen (Excel/PDF/CSV); this one renders one record
in full, the way you'd hand someone a printed copy of the request for an
audit or a change-management ticket.

Each router builds its own `sections` (grouped field lists, mirroring the
same DetailSection groupings already used on that module's Overview tab in
the frontend) and `history` (from the same qap_approval_actions log every
module already writes to and already shows on its own History tab), then
hands them to build_request_detail_pdf below -- so the reportlab boilerplate
(styles, table formatting, page setup) lives in exactly one place.
"""
import io
from typing import Iterable, List, Optional, Sequence, Tuple

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

_styles = getSampleStyleSheet()
_section_title_style = ParagraphStyle(
    "DetailSectionTitle", parent=_styles["Heading3"],
    spaceBefore=12, spaceAfter=5, textColor=colors.HexColor("#1f2937"), fontSize=11,
)
_meta_style = ParagraphStyle("DetailMeta", parent=_styles["Normal"], textColor=colors.HexColor("#4b5563"), fontSize=8.5)

Field = Tuple[str, object]
Section = Tuple[str, Sequence[Field]]
HistoryRow = Tuple[str, str, str, str, str, str]


def _fmt(value: object) -> str:
    if value is None or value == "":
        return "—"
    return str(value)


def build_request_detail_pdf(
    *, title: str, subtitle: str, sections: Iterable[Section],
    history: Sequence[HistoryRow], generated_by: str, generated_at: str,
    history_note: Optional[str] = None,
) -> io.BytesIO:
    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf, pagesize=A4, topMargin=16 * mm, bottomMargin=16 * mm, leftMargin=16 * mm, rightMargin=16 * mm,
        title=title,
    )
    elements: List = [
        Paragraph(title, _styles["Title"]),
        Paragraph(subtitle, _styles["Normal"]),
        Paragraph(f"Generated by {generated_by} on {generated_at}", _meta_style),
        Spacer(1, 10),
    ]

    for section_title, fields in sections:
        elements.append(Paragraph(section_title, _section_title_style))
        data = [[Paragraph(str(label), _styles["Normal"]), Paragraph(_fmt(value), _styles["Normal"])] for label, value in fields]
        if not data:
            continue
        t = Table(data, colWidths=[150, 330])
        t.setStyle(TableStyle([
            ("FONTSIZE", (0, 0), (-1, -1), 8.5),
            ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#d9dce3")),
            ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#f3f4f8")),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ("LEFTPADDING", (0, 0), (-1, -1), 5), ("RIGHTPADDING", (0, 0), (-1, -1), 5),
            ("TOPPADDING", (0, 0), (-1, -1), 3), ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
        ]))
        elements.append(t)
        elements.append(Spacer(1, 6))

    elements.append(Paragraph("Workflow / Approval History — Who Signed", _section_title_style))
    if history_note:
        elements.append(Paragraph(history_note, _meta_style))
        elements.append(Spacer(1, 4))
    if history:
        head = ["Step", "Decision", "Actor", "Role", "Comments", "When"]
        rows = [[Paragraph(_fmt(c), _styles["Normal"]) for c in row] for row in history]
        t = Table([head] + rows, repeatRows=1, colWidths=[70, 60, 75, 65, 140, 70])
        t.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1f2937")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTSIZE", (0, 0), (-1, -1), 7.5),
            ("GRID", (0, 0), (-1, -1), 0.4, colors.grey),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ("LEFTPADDING", (0, 0), (-1, -1), 4), ("RIGHTPADDING", (0, 0), (-1, -1), 4),
            ("TOPPADDING", (0, 0), (-1, -1), 3), ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
        ]))
        elements.append(t)
    else:
        elements.append(Paragraph("No workflow history recorded yet.", _styles["Normal"]))

    doc.build(elements)
    buf.seek(0)
    return buf
