"""Current user permission snapshot for System Administrator audit review."""
from __future__ import annotations

import io
from datetime import datetime
from zoneinfo import ZoneInfo

from sqlalchemy.orm import Session, selectinload

from . import models
from .constants import Role
from .workspace_service import selectable_workspace_ids


def _cell(value):
    if value is None:
        return ""
    if isinstance(value, str) and value.startswith(("=", "+", "-", "@")):
        return "'" + value
    return value


def _sheet(workbook, title: str, headers: list[str], rows: list[list], generated_at: str, actor: str):
    from openpyxl.styles import Alignment, Font, PatternFill
    from openpyxl.utils import get_column_letter

    sheet = workbook.create_sheet(title)
    sheet.append([title])
    sheet.append(["Generated at (IST)", generated_at])
    sheet.append(["Generated by", actor, "Rows", len(rows)])
    sheet.append(headers)
    for row in rows:
        sheet.append([_cell(value) for value in row])
    sheet.freeze_panes = "A5"
    sheet.auto_filter.ref = f"A4:{get_column_letter(len(headers))}{max(5, sheet.max_row)}"
    sheet.sheet_view.zoomScale = 90
    sheet["A1"].font = Font(size=16, bold=True, color="173B5C")
    for header_cell in sheet[4]:
        header_cell.fill = PatternFill("solid", fgColor="173B5C")
        header_cell.font = Font(bold=True, color="FFFFFF")
        header_cell.alignment = Alignment(vertical="center", wrap_text=True)
    sheet.row_dimensions[4].height = 34
    for column, header in enumerate(headers, 1):
        sheet.column_dimensions[get_column_letter(column)].width = min(46, max(17, len(header) + 4))
    for data_row in sheet.iter_rows(min_row=5):
        for cell in data_row:
            cell.alignment = Alignment(vertical="top", wrap_text=True)


def _access_source(user: models.User, workspace: models.QAWorkspace, assigned_roles: set[str]):
    direct = [membership.role for membership in user.qa_workspace_access
              if membership.workspace_id == workspace.id]
    if Role.ADMIN in assigned_roles:
        return "System Administrator", "Administrative access; workflow limited to own department and valid stage", direct, ""
    if Role.SCALE_6_PLUS in assigned_roles:
        return "Scale 6+", "Organization-wide read only", direct, ""
    if direct:
        grant = direct[0]
        level = {
            "WORKSPACE_MEMBER": "Direct member; permission profile and workflow gates apply",
            "WORKSPACE_VIEWER": "Direct viewer",
            "PARENT_WORKSPACE_VIEWER": "Parent viewer; read only across direct children",
            "PARENT_WORKSPACE_ADMIN": "Parent administrator; direct children included",
        }.get(grant, "Direct workspace grant; permission profile and workflow gates apply")
        return "Direct membership", level, direct, ""
    parent_id = workspace.parent_workspace_id
    parent_roles = [membership.role for membership in user.qa_workspace_access
                    if membership.workspace_id == parent_id]
    if "PARENT_WORKSPACE_ADMIN" in parent_roles:
        return "Inherited parent grant", "Parent administrator", direct, "PARENT_WORKSPACE_ADMIN"
    if "PARENT_WORKSPACE_VIEWER" in parent_roles:
        return "Inherited parent grant", "Read only", direct, "PARENT_WORKSPACE_VIEWER"
    coordinator = [assignment for assignment in user.department_coordinator_access
                   if assignment.workspace_id == parent_id]
    if coordinator:
        departments = ", ".join(sorted({assignment.department_name for assignment in coordinator
                                        if assignment.department_name}))
        return "Inherited coordinator scope", "Department-local administration; operational roles still apply", direct, departments
    return "Selectable workspace", "Permission profile and workflow gates apply", direct, ""


def user_access_workbook(db: Session, actor: models.User) -> io.BytesIO:
    """Export assigned grants and currently usable access without secrets."""
    from openpyxl import Workbook

    generated_at = datetime.now(ZoneInfo("Asia/Kolkata")).strftime("%d %b %Y, %H:%M:%S IST")
    users = db.query(models.User).options(
        selectinload(models.User.role_assignments),
        selectinload(models.User.department_assignments),
        selectinload(models.User.qa_workspace_memberships).selectinload(models.QAWorkspaceMember.workspace),
        selectinload(models.User.department_coordinator_assignments).selectinload(models.DepartmentCoordinatorAssignment.workspace),
        selectinload(models.User.department_coordinator_assignments).selectinload(models.DepartmentCoordinatorAssignment.department),
        selectinload(models.User.department_coordinator_assignments).selectinload(models.DepartmentCoordinatorAssignment.department_unit),
    ).order_by(models.User.full_name, models.User.id).all()
    workspaces = {workspace.id: workspace for workspace in db.query(models.QAWorkspace).all()}
    accounts: list[list] = []
    effective: list[list] = []
    grants: list[list] = []
    coordinators: list[list] = []
    for user in users:
        roles = {assignment.role for assignment in user.role_assignments}
        usable = bool(user.is_active and roles and not user.needs_role_review
                      and not user.needs_department_selection)
        accessible_ids = selectable_workspace_ids(db, user) if usable else set()
        accessible_ids = {workspace_id for workspace_id in accessible_ids
                          if workspace_id in workspaces and workspaces[workspace_id].is_active}
        preferred = workspaces.get(user.preferred_qa_workspace_id)
        accounts.append([
            user.id, user.username, user.full_name, user.email or "", user.login_type,
            "Active" if user.is_active else "Disabled",
            "Yes" if user.needs_role_review else "No",
            "Yes" if user.needs_department_selection else "No",
            ", ".join(user.departments), ", ".join(sorted(roles)),
            "Yes" if user.admin_managed_only else "No",
            "Yes" if user.show_in_user_dropdowns else "No",
            preferred.name if preferred else "", len(accessible_ids),
            user.created_at.isoformat(sep=" ") if user.created_at else "",
        ])
        for workspace_id in sorted(accessible_ids, key=lambda value: (workspaces[value].name.casefold(), value)):
            workspace = workspaces[workspace_id]
            source, level, direct_roles, inherited = _access_source(user, workspace, roles)
            parent = workspaces.get(workspace.parent_workspace_id)
            effective.append([
                user.id, user.username, workspace.id, workspace.workspace_key, workspace.name,
                parent.name if parent else "", source, level, ", ".join(direct_roles),
                inherited, ", ".join(user.departments), ", ".join(sorted(roles)),
            ])
        for membership in sorted(user.qa_workspace_memberships,
                                 key=lambda row: (row.workspace_id, row.role, row.id)):
            workspace = workspaces.get(membership.workspace_id)
            parent = workspaces.get(workspace.parent_workspace_id) if workspace else None
            grants.append([
                user.id, user.username, workspace.workspace_key if workspace else membership.workspace_id,
                workspace.name if workspace else "Deleted workspace", parent.name if parent else "",
                membership.role, "Active" if membership.is_active else "Inactive",
                "Active" if workspace and workspace.is_active else "Inactive",
                "Yes" if membership.is_active and membership.workspace_id in accessible_ids else "No",
                membership.created_at.isoformat(sep=" ") if membership.created_at else "",
            ])
        for assignment in sorted(user.department_coordinator_assignments, key=lambda row: row.id):
            workspace = workspaces.get(assignment.workspace_id)
            coordinators.append([
                user.id, user.username, workspace.workspace_key if workspace else assignment.workspace_id,
                workspace.name if workspace else "Deleted workspace",
                assignment.department_name or "", assignment.department_unit_name or "",
                "Active" if assignment.is_active else "Inactive",
                "Yes" if assignment.is_active and workspace and workspace.is_active
                and workspace.parent_workspace_id is None else "No",
            ])

    workbook = Workbook()
    workbook.remove(workbook.active)
    _sheet(workbook, "Accounts and Roles", [
        "User ID", "Username", "Full name", "Email", "Login type", "Account status",
        "Role review pending", "Department selection pending", "Departments", "Assigned roles",
        "Admin managed", "Shown in user pickers", "Preferred workspace",
        "Accessible workspace count", "Created at",
    ], accounts, generated_at, actor.username)
    _sheet(workbook, "Effective Workspace Access", [
        "User ID", "Username", "Workspace ID", "Workspace key", "Workspace name", "Parent workspace",
        "Access source", "Access level and limits", "Direct grant", "Inherited grant or department",
        "User departments", "Assigned roles",
    ], effective, generated_at, actor.username)
    _sheet(workbook, "Assigned Workspace Grants", [
        "User ID", "Username", "Workspace key", "Workspace name", "Parent workspace",
        "Assigned grant", "Grant status", "Workspace status", "Grant currently usable", "Granted at",
    ], grants, generated_at, actor.username)
    _sheet(workbook, "Coordinator Scopes", [
        "User ID", "Username", "Workspace key", "Workspace name", "Department",
        "Department unit", "Assignment status", "Inherits to direct children",
    ], coordinators, generated_at, actor.username)
    output = io.BytesIO()
    workbook.save(output)
    output.seek(0)
    return output
